### ISSUE TITLE
Incompatible with React Native 0.57

### ISSUE THREAD

**Issue by DimitryDushkin** [CRAlpha/react-native-wkwebview#194]
In 57 WkWebView support has been added and they using exact same file names and classes RCTWKWebView.m(h) so it won't compile now.

Seems like we should rename files and classes in this repo to be able to compile with React Native 0.57.

**Comment by jamonholmgren** [comment]
Per [this issue](https://github.com/CRAlpha/react-native-wkwebview/issues/191#issuecomment-422146121), I'd suggest looking at the new community-supported `react-native-webview`. While we aren't at feature parity with `react-native-wkwebview` (since we need to support Android and iOS as equally as possible), we are open to community PRs to bring in functionality you need.

https://github.com/react-native-community/react-native-webview

**Comment by insraq** [comment]
I will merge the PR after I am back from vacation.

**Comment by DimitryDushkin** [comment]
Related PR https://github.com/CRAlpha/react-native-wkwebview/pull/195
