### ISSUE TITLE
bidirectional communication using postMessage

### ISSUE THREAD

**Issue by baabgai** [CRAlpha/react-native-wkwebview#20]
Although undocumented, the UIWebView Component implements a postMessage command to communicate also from react native into the [webview](https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L474-L490).

It would be great after having the onMessage prop in place to have a communication channel for the other direction as well.

**Comment by fungilation** [comment]
It is documented, at least now: http://facebook.github.io/react-native/docs/webview.html

I also need bidirectional communication. RN's version in WebView is actually flakey and is being reworked, likely with an api like native.postMessage instead of window.postMessage (to not override existing window.postMessage that's on webpages communicating with iframes).

Anyhow. WKWebView.postMessage() from React Native back to webview would be fantastic and a true WebView replacement for me!

**Comment by insraq** [comment]
I have studied RN's implementation in WebView and to be frank, I don't really like it. It is too opinionated and intrusive to the web page.

To me, something that utilize `evaluateJavascript` should be good enough. It allows communication from native to JS and leaves the actual communication protocol to whoever uses the library.

I think we have the `evaluateJavascript` somewhere in our codebase, just need to extract it. I will probably take a look when I have got time.

**Comment by insraq** [comment]
This should have been fixed byt ca134c89a6aa7ec588609c524917d88d149dfced

**Comment by fungilation** [comment]
I'm confused with this. Is this actually `React Native -> WkWebView` as documented in README, or is it the other way around for bidirectional communication? (`WkWebView -> React Native`) Because with readme's sample code:
```
<WKWebView ref="webview" onLoadEnd={() => { this.refs.webview.evaluateJavaScript('document.title').then(console.log) }} />
```

console.log I assume would show up in RN's side, with webview's title. For actual React Native -> WkWebView, in a non-interactive way there is already `injectedJavaScript`?

Some more sample code please, if evaluateJavaScript enables full bidirectional communication.

**Comment by insraq** [comment]
You can uses `evaluateJavaScript` to pass message from React Native to WKWebView. A typical use case is as follows:

1. Define a global method in your web page like

```
window.receiveMessageFromReactNative = function(data) {
  // callback when received message from react native
}
```

2. Then in your React Native code, you can simply call

```
this.refs.webview.evaluateJavaScript('window.receiveMessageFromReactNative("Hello from React Native")')
```

Your webpage will receive the message.

**Comment by fungilation** [comment]
I see. But to be bidirectional, is there also a way for the webview to talk back to RN? Only with your example, to chain a `.then` so what's the returned value inside webview gets reported in RN, like `console.log`?

**Comment by fungilation** [comment]
You do have `onMessage` in the new README, I don't know how I missed it. Nevermind and thanks, looks great! I think I can use this as a full replacement for WebView, and you may potentially beat RN's native webview to a fully functional bidirectional communication (their version is bugged)
