### ISSUE TITLE
Load page from localhost in airplane mode

### ISSUE THREAD

**Issue by kesha-antonov** [CRAlpha/react-native-wkwebview#209]
Hello!

Is it possible to load page from localhost in airplane mode?
I get these errors: 1004 or 1009.

I run local server to show music player in webview. User caches audios and html,js,css. Opens app in airplane mode and see this error.

I think this is related: https://stackoverflow.com/questions/3209278/allow-uiwebview-to-load-http-localhostport-path-uris-without-an-internet-conn
https://stackoverflow.com/questions/33145077/using-nsurlprotocol-with-reactnative

**Comment by shirakaba** [comment]
Heya, I developed using react-native-wkwebview on localhost in airplane mode (whilst actually on a flight) for several hours. Indeed, I may have had a problem at first.

`Foundation/NSURLError.h` details those error codes (yes, they're negative numbers here, but disregard that):

```objc
NS_ERROR_ENUM(NSURLErrorDomain)
{
// ...
    NSURLErrorCannotConnectToHost = 		-1004,
// ...
    NSURLErrorNotConnectedToInternet = 		-1009,
```

The following function in `RCTWKWebView/RCTWKWebView.m` is fired when navigation fails due to an error; you may be able to comment out `_onLoadingError(event);` or simply call `return` early to prevent a red screen:

```objc
- (void)webView:(__unused WKWebView *)webView didFailProvisionalNavigation:(__unused WKNavigation *)navigation withError:(NSError *)error```

... But that may not get it to actually work.

For a start, can you successfully visit the same URL simply by using Safari? If that fails, then this component's got no chance.

**Comment by kesha-antonov** [comment]
@shirakaba Thanks!
1) Yes, I use your component 100%
2) I'll try visit same url in Safari
3) Is it possible to disable check for internet connection?

**Comment by kesha-antonov** [comment]
Didn't provide correct url
Now it works
Thanks!
