### ISSUE TITLE
Slow Page loading 

### ISSUE THREAD

**Issue by yonirabin** [CRAlpha/react-native-wkwebview#47]
Hello, 
Im using the CRAlpha react native wkwebview,
I have a fixed set of URLs, which the user can select and which should be displayed in the webview.
It takes a very long time for the webview to display the URLs, it seems to load all the page before displaying anything, so I just see the activity wheel until the whole page is loaded.

Note: the first page load is especially slow compared to the rest.

I'd like for there to be partial loading of the page, or even a convenient way to pre load/cache URLs

**Comment by insraq** [comment]
This component follows the default behavior of `WkWebView` for content caching.

There are few workarounds, you can either:

1. Download those pages and show local files instead of remote URL.
2. Have a hidden WKWebView component loading those pages when user is prompted with the select. And directly show the webpage when user has made the choice.

Also, if you prefer to show the webpage when it's still loading, **DO NOT** use `renderLoading` props, which overlays the actual webpage. Instead, build your own progress bar that does not cover the webpage.
