### ISSUE TITLE
Session cookies are not shared between instances

### ISSUE THREAD

**Issue by farazs** [CRAlpha/react-native-wkwebview#63]
Even with using `sendCookies`, different instances of WKWebView do not share cookies as the react-native WebWiew does. Using `sendCookies` works for most cookies but for some reason it does not work for session cookies set by the server.

See:
http://stackoverflow.com/questions/33156567/getting-all-cookies-from-wkwebview/34190447#34190447
http://stackoverflow.com/questions/25797972/cookie-sharing-between-multiple-wkwebviews
http://stackoverflow.com/questions/39772007/wkwebview-persistent-storage-of-cookies

**Comment by sportnak** [comment]
This may be correlated to general cookie bugs with WKWebView. I'm not super familiar with IOS so I can't actually tell you anything definitively. Based on https://bugs.webkit.org/show_bug.cgi?id=140191 it seems like a fix is in the pipeline. The solution I've come to today since trying to fix cookie related bugs is to set it in the injectedJavascript method on page load.

```
- (void)webView:(WKWebView *)webView didFinishNavigation:(__unused WKNavigation *)navigation
{
  NSDictionary *cookies = [NSHTTPCookie requestHeaderFieldsWithCookies:[[NSHTTPCookieStorage sharedHTTPCookieStorage] cookiesForURL:_action.request.URL]];
  [webView evaluateJavaScript:[NSString stringWithFormat:@"document.cookie='%@';", cookies[@"Cookie"]] completionHandler:^(id result, NSError *error) {}];
```

I've got cookies loading through the `- (void)loadRequest:(NSURLRequest *)request` on the first page, and then setting those cookies on subsequent requests [I've slightly modified it to check if my cookie is set first]. This seems to fix the problem of cookies not being persisted across pages. Again, not an IOS expert, so I defer to @insraq but this is how I got it working.

**Comment by sportnak** [comment]
Also note that I had to grab the navigation action in `decidePolicyForNavigation` by doing `_action = navigationAction;`. Definitely a hack, but maintains cookies adequately.

**Comment by farazs** [comment]
I have a PR to fix this see https://github.com/CRAlpha/react-native-wkwebview/pull/64

The issue is not that cookies are not persisted across pages. That works fine. 

The problem is when you have multiple instances of WKWebView they do not share cookies as the react-native WebView does. Using the `sendCookies` property partially fixes this but does not work for session cookies set by the server for example `JSESSIONID` cookie.

The fix for that is in the PR I created.

**Comment by sportnak** [comment]
Ah ok. Are you having users sign in via your webview or natively? What module are you using for cookie management? I'm doing it natively and trying to share cookies into the wkwebview but they only show up on initial page load.
